name: Python Secret Demo

on:
  push:
    branches: [ "main" ]

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Python file using secret
        run: python secret_demo.py
        env:
          MY_API_KEY: ${{ secrets.MY_API_KEY }}
